#!/usr/bin/env python3
import urllib.request
import json
import tempfile
import subprocess

wallpaper_change_script = """/usr/bin/osascript<<END
tell application "Finder"
set desktop picture to POSIX file "%s"
end tell
END"""

def set_desktop_background(filename):
    subprocess.call(wallpaper_change_script % filename, shell=True)

def bing_wallpaper_url():
    bing_base = "https://www.bing.com"
    market = "ja-JP"
    bing_api = "%s/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=%s" % (bing_base, market)
    response = json.load(urllib.request.urlopen(bing_api))
    return "%s%s%s" % (bing_base, response["images"][0]["urlbase"], "_UHD.jpg")

wallpaper_filename, _ = urllib.request.urlretrieve(bing_wallpaper_url())
set_desktop_background(wallpaper_filename)
