#!/usr/bin/env python3
import urllib.request
import json
import subprocess


def set_desktop_background(filename):
    osascript_stdin = (
        "\n".join(
            [
                'tell application "Finder"',
                f'set desktop picture to POSIX file "{filename}"',
                "end tell",
            ]
        )
    ).encode("utf-8")
    subprocess.run("/usr/bin/osascript", input=osascript_stdin)


def bing_wallpaper_url() -> str:
    bing_base = "https://www.bing.com"
    market = "ja-JP"
    bing_api = "%s/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=%s" % (bing_base, market)
    response = json.load(urllib.request.urlopen(bing_api))
    return "%s%s%s" % (bing_base, response["images"][0]["urlbase"], "_UHD.jpg")


wallpaper_filename, _ = urllib.request.urlretrieve(bing_wallpaper_url())
set_desktop_background(wallpaper_filename)
