#!/usr/bin/env python3
import urllib.request
import json
import subprocess
import shutil


def set_background_osascript(filename):
    osascript_stdin = (
        "\n".join(
            [
                'tell application "Finder"',
                f'set desktop picture to POSIX file "{filename}"',
                "end tell",
            ]
        )
    ).encode("utf-8")
    subprocess.run("osascript", input=osascript_stdin).check_returncode()


def set_background_feh(filename):
    subprocess.run(["feh", "--bg-fill", filename]).check_returncode()


def set_background(filename):
    background_commands_supported = {
        "osascript": set_background_osascript,
        "feh": set_background_feh,
    }

    for cmd, fn in background_commands_supported.items():
        if shutil.which(cmd):
            fn(filename)
            break


def bing_wallpaper_url() -> str:
    bing_base, market = "https://www.bing.com", "ja-JP"
    bing_api = f"{bing_base}/HPImageArchive.aspx?format=js&idx=0&n=1&mkt={market}"
    response = json.load(urllib.request.urlopen(bing_api))
    img_base = response["images"][0]["urlbase"]
    return f"{bing_base}{img_base}_UHD.jpg"


url = bing_wallpaper_url()
print(f'downloading from {url}')
wallpaper_filename, _ = urllib.request.urlretrieve(url)
set_background(wallpaper_filename)
